name: cybercheder
favicon: null
layout_spectrum: 0.9612726992927492
typography_spectrum: 0.25371355726383626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.27222458901815116
  lightness: 0.2882693037390709
  saturation: 0.6161206436809152
  rhythmicContrast: 0.42988754413090646
purpose: []
